### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by melodic16** [ThomasHeb/2AxisLaserCutter#4]
Hey Thomas, 

this is my setup, as you can see on the monitor I already upload the sketch,, but nothing happen.

![IMG_20230106_115308.jpg](https://user-images.githubusercontent.com/122068445/210932643-4e8ee9a2-4fb3-4c50-bca9-220548c14995.jpg) 

if need more photos pls let me know.

**Comment by ThomasHeb** [comment]
Good morning!
The display enclosure looks really good.
I see on your picture, that you connected DIR-, ENA- and PUL- to GND on the Arduino. This should work.
So I think, we should work through firmware and hardware to get the driver working.....

You will need the small button on the display next to the buzzer. you have a hole inside your enclosure. This button is the back button. The wheel on the display has a button, too.... this is the ok button.

**Test 1: Moving the stepper from the display**
I am not sure, if you understood my operating procedure on the display, so please let me explain:
- go to the POSITION menu, as on your picture
- on the lower end of the display, you see: "> Set laser dot on/off"
- turn the wheel to the right.... the text will disappear and you get a curser "^" under the Y-coordinates... see picture below.
- keep turning until the curser is on the mm position.
- press the wheel to select
- turn the wheel to change the position value

Sorry, it is complicated with only one wheel and two knobs.
The stepper should move a bit.....
![IMG_0470](https://user-images.githubusercontent.com/16707487/210959637-368bc68b-446b-4342-872f-4af59d86326a.jpg)

**Test 2: Moving the stepper via gcode**
You can connect your laptop and start the Serial Monitor in the Arduino IDE.
Select 115200 baud and the Com-Port (you will get a reset of the arduino... that is ok)
Moving the Laser in the POSITION Menu should send "ok" over the Com-Port

You can send code commands via the Serial Monitor, too:
- G91         this sets to relative position mode
- X1           this moves the X-Axis 1mm
After each command you should get an "ok"

**Test 3: Hardware**
- please check the GND connection to DIR-, ENA- and PUL- to GND from the Arduino GND
- please check the supply voltage to the driver
- please check the motor connections. remove the connector from the driver.... you should be able to turn the motor. connect A+ and A- from the motor, you should not be able to turn the motor anymore

**Test 4: Holding**
connect the motor to back to the driver, power everything up. are you able to turn the motors? At least, the motors should require much more force to rotate, while they are powered/controlled from the arduino.

**Test 5: Settings**
can you upload the config.h and defaults.h file?
best pack them in a zip and attach it here


P.S. how big do you plan your laser?..... I used the smallest NEMA17 motors ;o)


Best Regards
Thomas

**Comment by ThomasHeb** [comment]
Hi, 
I checked your picture again. and it seems, that you connected the driver to the wrong "positions" on the Ramps 1.6 board.
you need to use the positions which are marked with E0 and E1. 
![Bildschirmfoto 2023-01-06 um 11 48 40](https://user-images.githubusercontent.com/16707487/210998455-2f86a5bf-24c0-473b-9af1-6ca40fbd5a4f.png)
![Bildschirmfoto 2023-01-06 um 11 49 34](https://user-images.githubusercontent.com/16707487/210998460-e0d0771f-6f44-4208-a359-42ac070e166a.png)

Best Regards 
Thomas

**Comment by melodic16** [comment]
Hello

> Good morning! The display enclosure looks really good. I see on your picture, that you connected DIR-, ENA- and PUL- to GND on the Arduino. This should work. So I think, we should work through firmware and hardware to get the driver working.....
> 
> You will need the small button on the display next to the buzzer. you have a hole inside your enclosure. This button is the back button. The wheel on the display has a button, too.... this is the ok button.

Yes, I have that button maybe to small on the pic so it's like hole

> 
> **Test 1: Moving the stepper from the display** I am not sure, if you understood my operating procedure on the display, so please let me explain:
> 
> * go to the POSITION menu, as on your picture
> * on the lower end of the display, you see: "> Set laser dot on/off"
> * turn the wheel to the right.... the text will disappear and you get a curser "^" under the Y-coordinates... see picture below.
> * keep turning until the curser is on the mm position.
> * press the wheel to select
> * turn the wheel to change the position value
> 
> Sorry, it is complicated with only one wheel and two knobs. The stepper should move a bit..... ![IMG_0470](https://user-images.githubusercontent.com/16707487/210959637-368bc68b-446b-4342-872f-4af59d86326a.jpg)

Yes I understand and don't say sorry you are already helping me alot. I already try this but my motors not moving  

> 
> **Test 2: Moving the stepper via gcode** You can connect your laptop and start the Serial Monitor in the Arduino IDE. Select 115200 baud and the Com-Port (you will get a reset of the arduino... that is ok) Moving the Laser in the POSITION Menu should send "ok" over the Com-Port
> 
> You can send code commands via the Serial Monitor, too:
> 
> * G91         this sets to relative position mode
> * X1           this moves the X-Axis 1mm
>   After each command you should get an "ok"

Ok I will try this

> 
> **Test 3: Hardware**
> 
> * please check the GND connection to DIR-, ENA- and PUL- to GND from the Arduino GND
> * please check the supply voltage to the driver
> * please check the motor connections. remove the connector from the driver.... you should be able to turn the motor. connect A+ and A- from the motor, you should not be able to turn the motor anymore
> 
> **Test 4: Holding** connect the motor to back to the driver, power everything up. are you able to turn the motors? At least, the motors should require much more force to rotate, while they are powered/controlled from the arduino.
> 
> **Test 5: Settings** can you upload the config.h and defaults.h file? best pack them in a zip and attach it here

Ok

> 
> P.S. how big do you plan your laser?..... I used the smallest NEMA17 motors ;o)

I use nema34, it is quite big, the length of X axis is 5meters and Y axis is 2meters
I am not add the laser yet, just want to see the axis work 1st

> 
> Best Regards Thomas

sorry about your 2nd comments, so I should connect the driver to X axis to E0 and Y axis to E1?

**Comment by ThomasHeb** [comment]
Good morning!
X axis goes to E0, Y axis goes to E1.

Sorry this may be a bit confusing from the hardware connection perspective. This is a result of the shared code with the foam cutter. I am a bit afraid of changing the code, because I would need to do all the tests on both devices (laser and foam) again….. you know… never change a running system.

I would ask you to change the connection to E0 and E1.

You do not need to worry from the software side or from the gcode perspective. axis are controlled with X and Y and I did a successful test with light burn software, too.

Your dimensions are amazing. I would appreciate, if you share some pictures.
All the best for your project.

Best Regards
Thomas

**Comment by melodic16** [comment]
Hello Thomas,

> Good morning!
> X axis goes to E0, Y axis goes to E1.

![IMG_20230109_112427.jpg](https://user-images.githubusercontent.com/122068445/211240909-daa52e48-900f-4cd0-852d-92c0af4ed4e5.jpg)
and if I add limit switch, the red is for x axis and yellow for y axis?

> 
> Sorry this may be a bit confusing from the hardware connection perspective. This is a result of the shared code with the foam cutter. I am a bit afraid of changing the code, because I would need to do all the tests on both devices (laser and foam) again….. you know… never change a running system.
> 
> I would ask you to change the connection to E0 and E1.
> 
> You do not need to worry from the software side or from the gcode perspective. axis are controlled with X and Y and I did a successful test with light burn software, too.

Done, okay now my motors working. But somehow its skipping step/stalling at the start and the end of the rotation.
https://user-images.githubusercontent.com/122068445/211240495-84a9e661-aca4-405d-bc6a-c981f6cbfdd3.mp4
Sorry motor so rusty
I am very newbie on this kind of thing 
here the setting of the driver
![IMG_20230109_111400.jpg](https://user-images.githubusercontent.com/122068445/211240416-6c9c35c0-8088-4221-aed8-c8b06e47870c.jpg)

> 
> Your dimensions are amazing. I would appreciate, if you share some pictures.
> All the best for your project.

![IMG_20230109_111153.jpg](https://user-images.githubusercontent.com/122068445/211240607-16b96af8-308d-42c1-acb6-d20049044864.jpg)

> 
> Best Regards
> Thomas
> 

thank you

**Comment by melodic16** [comment]
Hello Thomas,

> Good morning!
> X axis goes to E0, Y axis goes to E1.

and if I want add limit switch I put on the default location? ![IMG_20230109_112856.jpg](https://user-images.githubusercontent.com/122068445/211241235-17a20042-2c6e-4c76-a0db-60f735143b98.jpg)

> 
> Sorry this may be a bit confusing from the hardware connection perspective. This is a result of the shared code with the foam cutter. I am a bit afraid of changing the code, because I would need to do all the tests on both devices (laser and foam) again….. you know… never change a running system.
> 
> I would ask you to change the connection to E0 and E1.
> 
> You do not need to worry from the software side or from the gcode perspective. axis are controlled with X and Y and I did a successful test with light burn software, too.

Done, okay now my motors working. But somehow its skipping step/stalling at the start and the end of the rotation.
https://user-images.githubusercontent.com/122068445/211240495-84a9e661-aca4-405d-bc6a-c981f6cbfdd3.mp4
Sorry motor so rusty
I am very newbie on this kind of thing 
here the setting of the driver
![IMG_20230109_111400.jpg](https://user-images.githubusercontent.com/122068445/211240416-6c9c35c0-8088-4221-aed8-c8b06e47870c.jpg)

> 
> Your dimensions are amazing. I would appreciate, if you share some pictures.
> All the best for your project.

![IMG_20230109_111153.jpg](https://user-images.githubusercontent.com/122068445/211240607-16b96af8-308d-42c1-acb6-d20049044864.jpg)

> 
> Best Regards
> Thomas
> 

thank you

**Comment by melodic16** [comment]
Hello Thomas,

> Good morning!
> X axis goes to E0, Y axis goes to E1.

and if I want add limit switch I put on the default location? ![IMG_20230109_112856.jpg](https://user-images.githubusercontent.com/122068445/211241235-17a20042-2c6e-4c76-a0db-60f735143b98.jpg)

> 
> Sorry this may be a bit confusing from the hardware connection perspective. This is a result of the shared code with the foam cutter. I am a bit afraid of changing the code, because I would need to do all the tests on both devices (laser and foam) again….. you know… never change a running system.
> 
> I would ask you to change the connection to E0 and E1.
> 
> You do not need to worry from the software side or from the gcode perspective. axis are controlled with X and Y and I did a successful test with light burn software, too.

Done, okay now my motors working. But somehow its skipping step/stalling at the start and the end of the rotation.
https://user-images.githubusercontent.com/122068445/211240495-84a9e661-aca4-405d-bc6a-c981f6cbfdd3.mp4
Sorry motor so rusty
I am very newbie on this kind of thing 
here the setting of the driver
![IMG_20230109_111400.jpg](https://user-images.githubusercontent.com/122068445/211240416-6c9c35c0-8088-4221-aed8-c8b06e47870c.jpg)

> 
> Your dimensions are amazing. I would appreciate, if you share some pictures.
> All the best for your project.

![IMG_20230109_113305.jpg](https://user-images.githubusercontent.com/122068445/211241533-e0f657e4-369e-4bf7-9c7d-14f9f0c73179.jpg)
here you can see my project

> 
> Best Regards
> Thomas
> 

thank you

**Comment by melodic16** [comment]
Hello Thomas

I already fix the skipping step/stalling at the start and the end of the rotation. I put the wrong cable on the driver, my bad.

**Comment by ThomasHeb** [comment]
Hello,

for the Limit switches check out the Hardware chapter
https://github.com/ThomasHeb/2AxisLaserCutter/tree/main/02_Hardware

- limit switch X-axis on X- S/- on Ramps (1st from left, top view) - this one is ok on your PCB
- limit switch Y-axis on X+ S/- on Ramps (2nd from left, top view) - this one needs to be moved one to the left on your PCB

The idea of the limit switches are to position the machine to a well defined 0,0 position.
If you wand to use position switches also on the max, max positions, you need to connect them in series:
- use normal closed (NC) limit switches, when you press them, they interrupt the current flow
- connect for X-Axis: S to first NC switch to second NC switch to -   ... on X- position
- connect for Y-Axis: S to first NC switch to second NC switch to -   ... on X+ position
![Bildschirmfoto 2023-01-09 um 09 36 52](https://user-images.githubusercontent.com/16707487/211268414-d33df99f-34d5-4dbc-b008-6a4930dd2a16.png)

due to your machine dimensions I would recommend to use the 100nF capacitors as in section hardware shown.
Maybe you need a shielded cable, too. connect shield to GND or - of the Arduino. But it is worth to do a test just with the 100nF.

Best Regards
Thomas

**Comment by melodic16** [comment]
Hi Thomas, sorry for late reply, I just work on another project. 

I just add the 100nF
![IMG_20230124_091231.jpg](https://user-images.githubusercontent.com/122068445/214214547-dd34fef4-75dd-43db-82d6-65ea46c2f8e8.jpg)

I operate the homing cycle, and if the limit switch triggered, arduino restarting. is that correct?

**Comment by ThomasHeb** [comment]
Helle, this is not correct. In homing cycles a Limit Switch should stop the motor and lead to some position movements. Please trigger the limit switch manually and check if your 5V is stable.  if your board resets, you have a short circuit from 5V to GND somehow.

the limit switch should connect GND (-) to the signal line (S).

**Comment by melodic16** [comment]
Hello 

I am using this ![IMG_20230125_170039.jpg](https://user-images.githubusercontent.com/122068445/214534945-a7367e7a-6781-4a51-bbd4-2822e61faf81.jpg)

![IMG_20230125_170023.jpg](https://user-images.githubusercontent.com/122068445/214535126-456cc38f-fb99-45cd-9214-5fe2d5699c48.jpg)

I try press manually the limit switch, the board restarted

**Comment by ThomasHeb** [comment]
Hello, I don't have these limit switch pcbs from makerbot here for testing. but never the less, the schematic should be like this.
![Bildschirmfoto 2023-01-25 um 17 24 24](https://user-images.githubusercontent.com/16707487/214619352-25df3849-7e6d-49e1-ad91-7668d8f943b7.png)
with this wiring and connection on your board, you connect black to green, when triggering. this means + / - or 5V and GND are connected directly.... this causes the voltage drop and CPU will restart after releasing the limit switch (please do not do this, this may damage your voltage regulator on the arduino board).

these limit switches operate as normal open (NO).... the firmware requires NC. if you have a broken cable, NO limit switch would not detect a limit/trigger, because of that safety reason I only use (and implemented) NC.

you can modify your limit switches in two ways:
- easy way, LED not working: connect green cable to S and red cable to -. Do not connect black cable


- cool way, LED should work: connect green cable to S and red cable to - and black cable to +. rotate the LED (remove from boards and change pads/pins). 
![Bildschirmfoto 2023-01-25 um 18 07 52](https://user-images.githubusercontent.com/16707487/214631959-b6dfe044-67b4-4d41-a7c3-a17f7b11123b.png)

- Please verify connection on Ramps carefully... position of red and green wire must be inverted and connector must be flipped
![214535126-456cc38f-fb99-45cd-9214-5fe2d5699c48](https://user-images.githubusercontent.com/16707487/214632197-73ed3be0-a3a1-41b7-9399-6704e7147c85.jpg)
